const actionTypes = Object.freeze({
  LOGIN: "LOGIN",
  SET_USERLOGIN: "SET_USERLOGIN",
  LOGOUT: "LOGOUT",
  FETCH_KHUTRO: "FETCH_KHUTRO",
  FETCH_PHONGTRO: "FETCH_PHONGTRO",
  FETCH_HOPDONG: "FETCH_HOPDONG",
  FETCH_PHULUC: "FETCH_PHULUC",
});

export default actionTypes;
