const actionTypes = Object.freeze({
  LOGIN: "LOGIN",
  SET_USERLOGIN: "SET_USERLOGIN",
  LOGOUT: "LOGOUT",
  FETCH_KHUTRO: "FETCH_KHUTRO",
  FETCH_PHONGTRO: "FETCH_PHONGTRO",
  FETCH_HOPDONG: "FETCH_HOPDONG",
  FETCH_PHULUC: "FETCH_PHULUC",
  SIGN_USER: "SIGN_USER",
  SET_CURRENT_KHUTRO: "SET_CURRENT_KHUTRO",
  FETCH_TIENICH_KHUTRO: "FETCH_TIENICH_KHUTRO",
});

export default actionTypes;
