export const PATH = {
  MANAGER_MOTEL: "/managermotel",
  LOGIN: "/",
  SIGNUP: "/signup",
  QLPHONG: "/quanlyphong",
  QLKHACHTHUE: "/quanlykhachthue",
  QLHOADDON: "/quanlyhoadon",
  QLPHIEUCHI: "/quanlyphieuchi",
  QLLICHXEMPHONG: "/quanlylichxemphong",
  BAOCAOKHUTRO: "/baocaokhutro",
  CAIDATKHUTRO: "/caidatkhutro",
  QLKHU: "/quanlykhu",
  TONGHOPBAOCAO: "/tonghopbaocao",
  NOTFOUNDPAGE: "*",
};
